groups:
  - - id: "start"
      icon: "start"
      text: "开始"
      action: "cmd_start"
      enabled_in: ["stopped", "error"]

    - id: "stop"
      icon: "stop"
      text: "暂停"
      action: "cmd_stop"
      enabled_in: ["running", "working", "starting", "auth"]

    - id: "restart"
      icon: "restart"
      text: "重启"
      action: "cmd_restart"
      enabled_in: ["running", "working", "starting", "auth", "error"]

    - id: "update"
      icon: "update"
      text: "更新"
      action: "cmd_default"
      enabled_in: ["all"]
      cmd: "update_app.bat"

  - - id: "status"
      icon: "status"
      text: "仪表板"
      action: "cmd_default"
      enabled_in: ["running", "working", "auth"]
      cmd: "show_web_window.bat"

    - id: "settings"
      icon: "settings"
      text: "配置文件"
      action: "cmd_default"
      enabled_in: ["all"]
      cmd: "settings.bat"

  - - id: "exit"
      icon: "exit"
      text: "退出"
      is_exit: true
      action: "cmd_exit"
      enabled_in: ["all"]
